### ISSUE TITLE
cmake 3.17.5 not supported

### ISSUE THREAD

**Issue by paisleyrob** [DEMCON/cmake-sbom#10]
https://github.com/DEMCON/cmake-sbom/blob/main/test/CMakeLists.txt#L21 indicates `3.5` is the minimum required version, but when using `3.17.5` `version.cmake` errors as follows:

```
CMake Error at cmake/version.cmake:249 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LINKER_LANGUAGE" is not allowed.
Call Stack (most recent call first):
  cmake/version.cmake:265 (version_generate)
  CMakeLists.txt:21 (include)
```

Removing that section seems to generate the same spdx output when using the newer CMake so it's not clear to me if it's even necessary.

**Comment by jhrutgers** [comment]
I think you are right. I have removed it.
