### ISSUE TITLE
Package name is stripped of any numbers

### ISSUE THREAD

**Issue by sithlord48** [DEMCON/cmake-sbom#11]
The Projects "Package" name is stripped of any numbers. This is done to make a clean SpdxID however the spec states 
`"SPDXRef-"[idstring]
where [idstring] is a unique string containing letters, numbers, ., and/or -.`

Propose that you change [`string(REGEX REPLACE "[^-A-Za-z.]+" "-" SBOM_GENERATE_PROJECT **"${SBOM_GENERATE_PROJECT}")`](https://github.com/DEMCON/cmake-sbom/blob/d09f5535620cb2c8b5580dc8a0b6951941da316d/cmake/sbom.cmake#L172C1-L172C91)
to
`string(REGEX REPLACE "[^-A-Za-z0-9.]+" "-" SBOM_GENERATE_PROJECT "${SBOM_GENERATE_PROJECT}")`

**Comment by jhrutgers** [comment]
You are right about the specs. This implementation made sure that there is no collision with other generated SPDXIDs later on. However, I have changed the implementation a bit, such that numbers are allowed now, but the collisions are still prevented.
